config/rbac/role.yaml, main.go, service/access_control_service.go, service/access_control_service_test.go
Signed-off-by: MD IMRAN <imranaec@outlook.com>
=> fix(): update worker cluster role for resourceSecret

CONTRIBUTING.md, code_of_conduct.md, developer_guide.md
Signed-off-by: MD IMRAN <imranaec@outlook.com>
=> doc(AM-4043): Open Source Documentation

service/worker_slice_gateway_service.go
Signed-off-by: Priyank Upadhyay <priyank@aveshasystems.com>
=> fix(): reverting changes for localGateway nodeIP

service/kube_slice_resource_names.go, util/reconciliation_utility.go
Signed-off-by: Puran Adhikari <puran.adhikari@aveshasystems.com>
Fixes #
```release-note
```
=> fix(): hotfix for roles verbs

Dockerfile, Makefile, cleanup/main.go, config/cleanup/cleanup_job.yaml, service/project_service.go, service/project_service_test.go, util/cleanup_utility.go, util/common.go, util/constants.go
* feat(AM-6038): added lables to Project CR
Signed-off-by: Priyank Upadhyay <priyank@aveshasystems.com>
* feat(AM-6038): added cleanup logic
Signed-off-by: Priyank Upadhyay <priyank@aveshasystems.com>
* feat(AM-6038): added cleanup command in makefile
Signed-off-by: Priyank Upadhyay <priyank@aveshasystems.com>
* feat(AM-6038): Refactors
Signed-off-by: Priyank Upadhyay <priyank@aveshasystems.com>
* feat(AM-6038): Refactors
Signed-off-by: Priyank Upadhyay <priyank@aveshasystems.com>
Signed-off-by: Priyank Upadhyay <priyank@aveshasystems.com>
Co-authored-by: Priyank Upadhyay <priyank@aveshasystems.com>
Fixes # …
=> fix(): Feature cleanup before uninstall (#101)

cleanup/main.go, cleanup/service/cleanup-service.go
- Refactored the cleanup service to allow method extension.
```release-note
```
=> fix(): cleanup service refactors

service/kube_slice_resource_names.go
=> fix(): permission issue for slice qos config resolve

README.md
- Fixed hyperlinks 
- Rephrased the doc
=> AM-6265: Update Kubeslice Controller readme file

cleanup/service/cleanup-service.go, config/cleanup/cleanup_job.yaml, service/cluster_service.go
- Removed flakiness of residuals on cleanup
- Added controller values to all secrets
```release-note
```
=> fix(): hotfix cleanup service removed flakiness

Jenkinsfile
- Updated Jenkinsfile for release pipeline
=> fix(): updated jenkinsfile

README.md
=> Update the KubeSlice Controller  README.md file

service/kube_slice_resource_names.go
Adding permissions to list events for readOnly and readWrite users.
Fixes #
```release-note
```
=> fix(): adding permission for events

service/worker_service_import_service.go
- Event raise issue resolution in worker service import
Fixes #
```release-note
```
=> fix(): service import event raise issue

util/reconciliation_utility.go
=> fix(): added a comment to bump the version

service/access_control_service.go, service/access_control_service_test.go
- default role binding event
Fixes #
```release-note
```
=> fix(): fix for default role binding event

service/cluster_service.go, service/cluster_service_test.go, service/cluster_webhook_validation.go, service/cluster_webhook_validation_test.go
* fix(AM-7432): added validations for NodeIPs
---------
Fixes #
```release-note
```
=> fix(AM-7432): added validations for NodeIPs (#144)

Makefile, config/crd/bases/controller.kubeslice.io_clusters.yaml, config/crd/bases/controller.kubeslice.io_projects.yaml, config/crd/bases/controller.kubeslice.io_serviceexportconfigs.yaml, config/crd/bases/controller.kubeslice.io_sliceconfigs.yaml, config/crd/bases/controller.kubeslice.io_sliceqosconfigs.yaml, config/crd/bases/worker.kubeslice.io_workerserviceimports.yaml, config/crd/bases/worker.kubeslice.io_workersliceconfigs.yaml, config/crd/bases/worker.kubeslice.io_workerslicegateways.yaml, config/crd/bases/worker.kubeslice.io_workerslicegwrecyclers.yaml, config/rbac/role.yaml, config/webhook/manifests.yaml
Modified `Makefile` to install `controller-gen v0.11.1` and `kustomize v3.8.7` as a fix for `make generate` command.
Fixes #
```release-note
```
=> fix(): makefile modifications

Jenkinsfile
=> fix(): release latest images

controllers/controller/cluster_controller_test.go, controllers/controller/project_controller_test.go, controllers/controller/suite_test.go, service/namespace_service.go
=> fix(): project integration tests added

Makefile, service/slice_config_webhook_validation.go, service/slice_config_webhook_validation_test.go, service/vpn_key_rotation_service.go, service/vpn_key_rotation_service_test.go
=> handle rotationinterval updates in reconciler

README.md
Changed the doc hyperlinks in the ReadMe file.
Fixes #
```release-note
```
=> Changed the doc hyperlinks in the ReadMe file

code_of_conduct.md
=> doc(): broken link fix

apis/controller/v1alpha1/sliceconfig_types.go, apis/worker/v1alpha1/workersliceconfig_types.go, apis/worker/v1alpha1/workerslicegateway_types.go, config/crd/bases/controller.kubeslice.io_sliceconfigs.yaml, config/crd/bases/worker.kubeslice.io_workersliceconfigs.yaml, config/crd/bases/worker.kubeslice.io_workerslicegateways.yaml, service/kube_slice_resource_names.go, service/mocks/IWorkerSliceGatewayService.go, service/service_helper.go, service/slice_config_service.go, service/slice_config_webhook_validation.go, service/slice_config_webhook_validation_test.go, service/vpn_key_rotation_service.go, service/vpn_key_rotation_service_test.go, service/worker_slice_config_service.go, service/worker_slice_gateway_service.go
define protocol for slice gateway external loadbalancer
```release-note
```
=> feat(AM-11741): protocol specification for slice gateway load balancer

apis/controller/v1alpha1/serviceexportconfig_types.go, apis/controller/v1alpha1/sliceconfig_types.go, apis/worker/v1alpha1/workerserviceimport_types.go, apis/worker/v1alpha1/workersliceconfig_types.go, config/crd/bases/controller.kubeslice.io_serviceexportconfigs.yaml, config/crd/bases/controller.kubeslice.io_sliceconfigs.yaml, config/crd/bases/worker.kubeslice.io_workerserviceimports.yaml, config/crd/bases/worker.kubeslice.io_workersliceconfigs.yaml, service/worker_service_import_service.go
Multi-net deployment with envoy gateway
NA
```release-note
```
=> feat(AM-12243): controller changes for envoy gw

README.md
=> Updated the latest doc hyperlinks in this README.md

service/slice_config_webhook_validation.go
=> fix(): overlay network change

README.md
=> Update README.md with badges 
